### ISSUE TITLE
Tracking Issue: Testing

### ISSUE THREAD

**Issue by spacekookie** [novelistapp/novelist#11]
`novelist` will end up being very complex and as such we should worry about testing _early_. What is there to test?

- File I/O logic
- Various text logic elements in `novelist-core`
- UI event hookups in `novelist-gtk`
- Macro expansions from `novelist-codegen` ?

Most of these are """easy""" to test. How can we test `relm`-`gtk` code?

**Comment by spacekookie** [comment]
## Testing File I/O

- [ ] Creating a project
- [ ] Loading a project
- [ ] Writing a file & loading it
- [ ] Creating chapters with multiple files
- [ ] Moving files from one chapter to the next
- [ ] Adding files to the universe

## Testing text logic

- [ ] ???

## Testing UI actor logic

- [ ] ?!?!?!?
